package de.tyro.project11;

import de.tyro.project11.registration.AdministratorInitializer;
import de.tyro.project11.registration.UserRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.DefaultApplicationArguments;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.test.context.ContextConfiguration;

import java.sql.DriverManager;
import java.sql.SQLException;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(properties = "spring.datasource.url=jdbc:h2:mem:schema-upgrade-test;DB_CLOSE_DELAY=-1")
@ContextConfiguration(initializers = SchemaUpgradeIntegrationTests.LegacyDatabase.class)
class SchemaUpgradeIntegrationTests {

    @Autowired UserRepository users;
    @Autowired AdministratorInitializer administrators;

    @Test
    void hibernateUpgradesPopulatedLegacyTableAndBootstrapsAdministrator() {
        var first = users.findByEmail("first@example.com").orElseThrow();
        var second = users.findByEmail("second@example.com").orElseThrow();
        assertThat(users.count()).isEqualTo(2);
        assertThat(first.getDisplayName()).isEqualTo("First User");
        assertThat(first.getPasswordHash()).isEqualTo("existing-hash");
        assertThat(first.getCreatedAt().getYear()).isEqualTo(2025);
        assertThat(first.isAdmin()).isTrue();
        assertThat(second.isAdmin()).isFalse();
        assertThat(first.getTallyCount()).isZero();
        assertThat(second.getTallyCount()).isZero();
        assertThat(first.getCredentialVersion()).isZero();

        // Subsequent startup initialization must preserve an administrator chosen in the UI.
        first.setAdmin(false);
        second.setAdmin(true);
        second.setTallyCount(7);
        users.save(first);
        users.save(second);
        administrators.run(new DefaultApplicationArguments());
        assertThat(users.findById(first.getId()).orElseThrow().isAdmin()).isFalse();
        var retained = users.findById(second.getId()).orElseThrow();
        assertThat(retained.isAdmin()).isTrue();
        assertThat(retained.getTallyCount()).isEqualTo(7);
    }

    static class LegacyDatabase implements ApplicationContextInitializer<ConfigurableApplicationContext> {
        @Override
        public void initialize(ConfigurableApplicationContext context) {
            // Reproduce the populated schema from before admin roles and tallies existed.
            try (var connection = DriverManager.getConnection(
                    context.getEnvironment().getRequiredProperty("spring.datasource.url"), "sa", "");
                 var statement = connection.createStatement()) {
                statement.execute("""
                        CREATE TABLE app_users (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            display_name VARCHAR(80) NOT NULL,
                            email VARCHAR(254) NOT NULL,
                            password_hash VARCHAR(100) NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT uk_app_users_email UNIQUE (email)
                        )
                        """);
                statement.execute("""
                        INSERT INTO app_users (display_name, email, password_hash, created_at) VALUES
                        ('First User', 'first@example.com', 'existing-hash', TIMESTAMP WITH TIME ZONE '2025-01-01 00:00:00+00'),
                        ('Second User', 'second@example.com', 'existing-hash', TIMESTAMP WITH TIME ZONE '2025-01-02 00:00:00+00')
                        """);
            } catch (SQLException exception) {
                throw new IllegalStateException("Could not prepare the legacy test database", exception);
            }
        }
    }
}
